#!/bin/bash

# The environment setup script
# Based on https://github.com/hyneq/wea-projekt/blob/main/backend/setup.sh
# and https://github.com/hyneq/STINBankSystem/blob/main/dev_setup.sh

# Load variables and cd to project_root
source "$(dirname "$0")"/vars
cd "$project_root"

mode="$1"
if [[ "$mode" != "deploy" && "$mode" != "dev" ]]; then
    echo "usage: $0 dev|deploy" >&2 && exit 1
fi

# Define setup mode
export SETUP_MODE="$mode"

# Create a venv with test dependencies and activate it
if [[ -z "$NO_CREATE_VENV" ]]; then
    "$project_root/create_venv.sh"
    source "$project_root/activate"
fi

# Create a deployment-specific configuration file
cat << EOF > "$app_dir/settings.py"
# Auto-generated by $(realpath $0)

DEBUG = True

EOF

# Create a secret key
"$project_root/gen_secret_key.sh"

# Initialize a database
"$app_dir/manage.py" migrate
