#!/bin/bash

# The environment setup script
# Based on https://github.com/hyneq/wea-projekt/blob/main/backend/setup.sh
# and https://github.com/hyneq/STINBankSystem/blob/main/dev_setup.sh

# Load variables and cd to project_root
source "$(dirname "$0")"/vars
cd "$project_root"

mode="$1"
if [[ "$mode" != "deploy" && "$mode" != "dev" ]]; then
    echo "usage: $0 dev|deploy" >&2 && exit 1
fi

# Define setup mode
export SETUP_MODE="$mode"

# Create a venv with test dependencies and activate it
if [[ -z "$SETUP_NO_VENV" ]]; then
    "$project_root/create_venv.sh"
    source "$project_root/activate"
fi

case "$mode" in
    dev)
        # Create an instance-specific configuration file
        cat << EOF > "$app_dir/settings.py"
# Auto-generated by $(realpath $0)

DEBUG = True

EOF
        ;;

    deploy)
        # Prompt the user to manually create an instance-specific configuration file
        echo "$0: For deploy setup mode, you need to manually create \"$app_dir/settings.py\" containing instance-specific configuration." >&2
        ;;
esac

# Create a secret key
"$project_root/gen_secret_key.sh"

# Initialize a database
"$app_dir/manage.py" migrate
